import React, { Component } from 'react'
import { Page } from '../components/base/Page'

export function Login() {
  return (
    <Page>
      <pre>
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
        Login
      </pre>
    </Page>
  )
}